import type { Locale, ResearchVerdict, Stage } from "../types/domain";

const copy = {
  "zh-CN": {
    brandTag: "开源现实检验 · 三文件交付",
    reset: "清空本地会话",
    live: "实时 API",
    demo: "演示数据",
    stages: ["定义想法", "确认 BRIEF", "开源审查", "确认 PLAN", "生成 RULES", "完成"],
    startEyebrow: "在写代码之前，先把方向说清楚",
    startTitle: "一个想法。一次现实检验。三个可执行文件。",
    startLead: "Project Bootstrap 帮你收紧模糊需求，用 GitHub 证据检查已有方案，再生成后续 AI 真正需要的 BRIEF、PLAN 与 RULES。",
    ideaLabel: "你想做什么？",
    ideaPlaceholder: "例如：帮自由设计师整理客户素材，并在交付前检查遗漏……",
    language: "语言",
    mode: "运行模式",
    modeHelp: "演示数据可离线走完全流程；实时 API 使用服务端模型与 GitHub 配置。",
    begin: "开始定义项目",
    examples: "试试示例",
    exampleItems: ["给独立咖啡店做一个不过度营销的排班工具", "把散落的访谈记录整理为可检索的产品洞察", "为自由设计师检查客户交付物是否齐全"],
    workspace: "项目工作台",
    draftReady: "草案已生成。请检查事实与边界，确认后才会进入下一阶段。",
    revise: "编辑当前文件",
    saveRevision: "保存修订",
    cancel: "取消",
    confirmBrief: "确认 BRIEF，开始开源审查",
    generatePlan: "生成 PLAN",
    confirmPlan: "确认 PLAN，生成 RULES",
    loadingBrief: "正在整理边界与最小可行范围…",
    loadingResearch: "正在读取仓库证据并区分事实、作者声称与推断…",
    loadingPlan: "正在把已确认的范围转为实施路线…",
    loadingRules: "正在生成权限、上下文与验收规则…",
    researchTitle: "开源现实检验",
    researchLead: "先看结论与限制，再决定哪些建议值得进入正式文件。",
    limitations: "本次限制",
    advantages: "当前优势",
    weaknesses: "明显不足",
    reusableIdeas: "可复用内容",
    differentiation: "差异化建议",
    repositories: "相关仓库",
    evidence: "查看证据",
    confirmedCapabilities: "已确认能力",
    licenseMissing: "未检测到许可证 · 不应复用代码",
    licenseCaveat: "许可证仅为自动检测结果与一般提醒，不构成法律意见。",
    useful: "可借鉴",
    avoid: "不建议照搬",
    difference: "与你的差异",
    suggestedChanges: "可选变更",
    affects: "影响",
    applyContinue: "应用所选变更并继续",
    skip: "跳过调研，继续生成 PLAN",
    selectedSummary: "将应用的变更",
    noSelection: "尚未选择任何变更；正式文件不会被静默修改。",
    resultTitle: "三个文件已就绪",
    resultLead: "规划到此结束。后续开发只需按任务读取必要文件。",
    copy: "复制",
    copied: "已复制",
    download: "下载",
    downloadZip: "下载全部 ZIP",
    editBrief: "返回修改 BRIEF",
    editPlan: "返回修改 PLAN",
    retry: "重试上一步",
    errorTitle: "这一步没有完成",
    confirmed: "已确认",
    draft: "待确认",
    revision: "修订",
  },
  en: {
    brandTag: "Open-source reality check · Three-file handoff",
    reset: "Clear local session",
    live: "Live API",
    demo: "Demo data",
    stages: ["Define idea", "Confirm BRIEF", "Reality check", "Confirm PLAN", "Generate RULES", "Done"],
    startEyebrow: "Get the direction right before writing code",
    startTitle: "One idea. One reality check. Three executable files.",
    startLead: "Project Bootstrap tightens a rough requirement, checks existing work using GitHub evidence, then creates the BRIEF, PLAN, and RULES that later AI actually needs.",
    ideaLabel: "What do you want to build?",
    ideaPlaceholder: "For example: help freelance designers organize client assets and catch missing deliverables…",
    language: "Language",
    mode: "Run mode",
    modeHelp: "Demo data completes the flow offline. Live API uses the server-side model and GitHub configuration.",
    begin: "Define the project",
    examples: "Try an example",
    exampleItems: ["A scheduling tool for independent cafés without growth bloat", "Turn scattered interviews into searchable product insights", "Check client deliverables for freelance designers"],
    workspace: "Project workspace",
    draftReady: "The draft is ready. Review facts and boundaries; the next stage requires explicit confirmation.",
    revise: "Edit current file",
    saveRevision: "Save revision",
    cancel: "Cancel",
    confirmBrief: "Confirm BRIEF and check open source",
    generatePlan: "Generate PLAN",
    confirmPlan: "Confirm PLAN and generate RULES",
    loadingBrief: "Defining boundaries and the smallest viable scope…",
    loadingResearch: "Reading repository evidence and separating facts, author claims, and inference…",
    loadingPlan: "Turning confirmed scope into an implementation route…",
    loadingRules: "Generating permission, context, and acceptance rules…",
    researchTitle: "Open-source reality check",
    researchLead: "Read the verdict and limitations first, then choose what belongs in formal files.",
    limitations: "Limitations",
    advantages: "Current advantages",
    weaknesses: "Clear weaknesses",
    reusableIdeas: "Reusable ideas",
    differentiation: "Differentiation guidance",
    repositories: "Related repositories",
    evidence: "View evidence",
    confirmedCapabilities: "Confirmed capabilities",
    licenseMissing: "No license detected · do not reuse code",
    licenseCaveat: "License labels are automated detection and general guidance, not legal advice.",
    useful: "Useful reference",
    avoid: "Do not copy",
    difference: "Difference from your project",
    suggestedChanges: "Optional changes",
    affects: "Affects",
    applyContinue: "Apply selected changes and continue",
    skip: "Skip research and continue to PLAN",
    selectedSummary: "Changes to apply",
    noSelection: "No changes selected. Formal files will not be modified silently.",
    resultTitle: "Three files are ready",
    resultLead: "Planning stops here. Later work should load only the file needed for the task.",
    copy: "Copy",
    copied: "Copied",
    download: "Download",
    downloadZip: "Download all as ZIP",
    editBrief: "Return to BRIEF",
    editPlan: "Return to PLAN",
    retry: "Retry previous step",
    errorTitle: "This step did not complete",
    confirmed: "Confirmed",
    draft: "Awaiting confirmation",
    revision: "Revision",
  },
} as const;

export const getCopy = (locale: Locale) => copy[locale];

export const stageIndex = (stage: Stage): number => ({
  idea_input: 0,
  brief_clarification: 0,
  brief_review: 1,
  research_loading: 2,
  research_review: 2,
  plan_review: 3,
  rules_generation: 4,
  completed: 5,
  recoverable_error: 0,
})[stage];

export function verdictLabel(locale: Locale, verdict: ResearchVerdict): string {
  const labels: Record<ResearchVerdict, [string, string]> = {
    continue: ["可以继续", "Continue"],
    continue_with_focus: ["聚焦后继续", "Continue with focus"],
    redefine_differentiation: ["先重定义差异", "Redefine differentiation"],
    pause_for_evidence: ["等待关键证据", "Pause for evidence"],
  };
  return labels[verdict][locale === "zh-CN" ? 0 : 1];
}
